# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: 'Aselo Development release custom action'
description: 'Sets up environment variables related to non-standard additional features in use in the development environment'
inputs:
  account-sid:
    description: 'The Twilio Account SID for this account'
    required: true
runs:
  using: "composite"
  steps:
    # Set IWF credentials
    - name: Set IWF_API_USERNAME
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: IWF_API_USERNAME
        env_variable_name: "IWF_API_USERNAME"
    - name: Set IWF_API_PASSWORD
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: IWF_API_PASSWORD
        env_variable_name: "IWF_API_PASSWORD"
    - name: Set IWF_API_URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "IWF_API_URL"
        env_variable_name: "IWF_API_URL"
      # - name: Set IWF_API_ENVIRONMENT
      #   uses: "marvinpinto/action-inject-ssm-secrets@latest"
      #   with:
      #     ssm_parameter: "DEV_AS_IWF_API_ENVIRONMENT"
      #     env_variable_name: "IWF_API_ENVIRONMENT"
      # - name: Set IWF_API_COUNTRY_CODE
      #   uses: "marvinpinto/action-inject-ssm-secrets@latest"
      #   with:
      #     ssm_parameter: "DEV_AS_IWF_API_COUNTRY_CODE"
      #     env_variable_name: "IWF_API_COUNTRY_CODE"

    - name: Set IWF_SECRET_KEY
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: /development/iwf/${{inputs.account-sid}}/secret_key
        env_variable_name: "IWF_SECRET_KEY"
    - name: Set IWF_API_CASE_URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: /development/iwf/${{inputs.account-sid}}/api_case_url
        env_variable_name: "IWF_API_CASE_URL"
    - name: Set IWF_REPORT_URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: /development/iwf/${{inputs.account-sid}}/report_url
        env_variable_name: "IWF_REPORT_URL"

    - name: Set Aselo Facebook App Secret
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "FACEBOOK_APP_SECRET"
        env_variable_name: "FACEBOOK_APP_SECRET"
    - name: Set helpline Facebook Page Access Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "FACEBOOK_PAGE_ACCESS_TOKEN_105220114492262_Aselo-Development"
        env_variable_name: "FACEBOOK_PAGE_ACCESS_TOKEN"
    - name: Set helpline Instagram Flex Flow SID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "DEV_TWILIO_AS_INSTAGRAM_FLEX_FLOW_SID"
        env_variable_name: "INSTAGRAM_FLEX_FLOW_SID"
    # Line environment variables
    - name: Set helpline Line Flex Flow SID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "DEV_TWILIO_AS_LINE_FLEX_FLOW_SID"
        env_variable_name: "LINE_FLEX_FLOW_SID"
    - name: Set Line Channel Secret
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/development/line/${{inputs.account-sid}}/channel_secret"
        env_variable_name: "LINE_CHANNEL_SECRET"
    - name: Set Line Channel Access Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/development/line/${{inputs.account-sid}}/channel_access_token"
        env_variable_name: "LINE_CHANNEL_ACCESS_TOKEN"
    # Line environment variables
    - name: Set helpline Line Flex Messaging Mode (Programmable Chat or Conversations)
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/development/line/${{inputs.account-sid}}/messaging_mode"
        env_variable_name: "LINE_TWILIO_MESSAGING_MODE"
    # Modica environment variables
    - name: Set Modica App Name
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/development/modica/${{inputs.account-sid}}/app_name"
        env_variable_name: "MODICA_APP_NAME"
    - name: Set Modica App Password
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/development/modica/${{inputs.account-sid}}/app_password"
        env_variable_name: "MODICA_APP_PASSWORD"
    - name: Set Modica Flex Flow Sid
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/development/twilio/${{inputs.account-sid}}/modica_flex_flow_sid"
        env_variable_name: "MODICA_FLEX_FLOW_SID"
    # Append environment variables
    - name: Add IWF_API_USERNAME
      run: echo "IWF_API_USERNAME=${{ env.IWF_API_USERNAME }}" >> .env
      shell: bash
    - name: Add IWF_API_PASSWORD
      run: echo "IWF_API_PASSWORD=${{ env.IWF_API_PASSWORD }}" >> .env
      shell: bash
    - name: Add IWF_API_URL
      run: echo "IWF_API_URL=${{ env.IWF_API_URL }}" >> .env
      shell: bash

    - name: Add IWF_SECRET_KEY
      run: echo "IWF_SECRET_KEY=${{ env.IWF_SECRET_KEY }}" >> .env
      shell: bash
    - name: Add IWF_API_CASE_URL
      run: echo "IWF_API_CASE_URL=${{ env.IWF_API_CASE_URL }}" >> .env
      shell: bash
    - name: Add IWF_REPORT_URL
      run: echo "IWF_REPORT_URL=${{ env.IWF_REPORT_URL }}" >> .env
      shell: bash
    - name: Add FACEBOOK_APP_SECRET
      run: echo "FACEBOOK_APP_SECRET=${{ env.FACEBOOK_APP_SECRET }}" >> .env
      shell: bash
    - name: Add FACEBOOK_PAGE_ACCESS_TOKEN
      run: echo "FACEBOOK_PAGE_ACCESS_TOKEN=${{ env.FACEBOOK_PAGE_ACCESS_TOKEN }}" >> .env
      shell: bash
    - name: Add INSTAGRAM_FLEX_FLOW_SID
      run: echo "INSTAGRAM_FLEX_FLOW_SID=${{ env.INSTAGRAM_FLEX_FLOW_SID }}" >> .env
      shell: bash
    - name: Add LINE_FLEX_FLOW_SID
      run: echo "LINE_FLEX_FLOW_SID=${{ env.LINE_FLEX_FLOW_SID }}" >> .env
      shell: bash
    - name: Add LINE_CHANNEL_SECRET
      run: echo "LINE_CHANNEL_SECRET=${{ env.LINE_CHANNEL_SECRET }}" >> .env
      shell: bash
    - name: Add LINE_CHANNEL_ACCESS_TOKEN
      run: echo "LINE_CHANNEL_ACCESS_TOKEN=${{ env.LINE_CHANNEL_ACCESS_TOKEN }}" >> .env
      shell: bash
    - name: Add MODICA_APP_NAME
      run: echo "MODICA_APP_NAME=${{ env.MODICA_APP_NAME }}" >> .env
      shell: bash
    - name: Add MODICA_APP_PASSWORD
      run: echo "MODICA_APP_PASSWORD=${{ env.MODICA_APP_PASSWORD }}" >> .env
      shell: bash
    - name: Add MODICA_FLEX_FLOW_SID
      run: echo "MODICA_FLEX_FLOW_SID=${{ env.MODICA_FLEX_FLOW_SID }}" >> .env
      shell: bash
