name: 'Aselo Development release custom action'
description: 'Sets up environment variables related to non-standard additional features in use in the development environment'
inputs:
  account-sid:
    description: 'The Twilio Account SID for this account'
    required: true
runs:
  using: "composite"
  steps:
    # Set IWF credentials
    - name: Set IWF_API_USERNAME
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: IWF_API_USERNAME
        env_variable_name: "IWF_API_USERNAME"
    - name: Set IWF_API_PASSWORD
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: IWF_API_PASSWORD
        env_variable_name: "IWF_API_PASSWORD"
    - name: Set IWF_API_URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "IWF_API_URL"
        env_variable_name: "IWF_API_URL"
      # - name: Set IWF_API_ENVIRONMENT
      #   uses: "marvinpinto/action-inject-ssm-secrets@latest"
      #   with:
      #     ssm_parameter: "DEV_AS_IWF_API_ENVIRONMENT"
      #     env_variable_name: "IWF_API_ENVIRONMENT"
      # - name: Set IWF_API_COUNTRY_CODE
      #   uses: "marvinpinto/action-inject-ssm-secrets@latest"
      #   with:
      #     ssm_parameter: "DEV_AS_IWF_API_COUNTRY_CODE"
      #     env_variable_name: "IWF_API_COUNTRY_CODE"

    - name: Set IWF_SECRET_KEY
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: /development/iwf/${{inputs.account-sid}}/secret_key
        env_variable_name: "IWF_SECRET_KEY"
    - name: Set IWF_API_CASE_URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: /development/iwf/${{inputs.account-sid}}/api_case_url
        env_variable_name: "IWF_API_CASE_URL"
    - name: Set IWF_REPORT_URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: /development/iwf/${{inputs.account-sid}}/report_url
        env_variable_name: "IWF_REPORT_URL"

    - name: Set Aselo Twitter Consumer Key
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "TWITTER_CONSUMER_KEY"
        env_variable_name: "TWITTER_CONSUMER_KEY"
    - name: Set Aselo Twitter Consumer Secret
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "TWITTER_CONSUMER_SECRET"
        env_variable_name: "TWITTER_CONSUMER_SECRET"
    - name: Set helpline Twitter Access Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "TWITTER_ACCESS_TOKEN_1398343158954663937_AseloDev"
        env_variable_name: "TWITTER_ACCESS_TOKEN"
    - name: Set helpline Twitter Access Secret
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "TWITTER_ACCESS_TOKEN_SECRET_1398343158954663937_AseloDev"
        env_variable_name: "TWITTER_ACCESS_TOKEN_SECRET"
    - name: Set helpline Twitter Flex Flow SID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "DEV_TWILIO_AS_TWITTER_FLEX_FLOW_SID"
        env_variable_name: "TWITTER_FLEX_FLOW_SID"
    - name: Set Aselo Facebook App Secret
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "FACEBOOK_APP_SECRET"
        env_variable_name: "FACEBOOK_APP_SECRET"
    - name: Set helpline Facebook Page Access Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "FACEBOOK_PAGE_ACCESS_TOKEN_105220114492262_Aselo-Development"
        env_variable_name: "FACEBOOK_PAGE_ACCESS_TOKEN"
    - name: Set helpline Instagram Flex Flow SID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "DEV_TWILIO_AS_INSTAGRAM_FLEX_FLOW_SID"
        env_variable_name: "INSTAGRAM_FLEX_FLOW_SID"
    # Line environment variables
    - name: Set helpline Line Flex Flow SID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "DEV_TWILIO_AS_LINE_FLEX_FLOW_SID"
        env_variable_name: "LINE_FLEX_FLOW_SID"
    - name: Set Line Channel Secret
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "DEV_LINE_AS_CHANNEL_SECRET"
        env_variable_name: "LINE_CHANNEL_SECRET"
    - name: Set Line Channel Access Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "DEV_LINE_AS_CHANNEL_ACCESS_TOKEN"
        env_variable_name: "LINE_CHANNEL_ACCESS_TOKEN"
    # Append environment variables
    - name: Add IWF_API_USERNAME
      run: echo "IWF_API_USERNAME=${{ env.IWF_API_USERNAME }}" >> .env
      shell: bash
    - name: Add IWF_API_PASSWORD
      run: echo "IWF_API_PASSWORD=${{ env.IWF_API_PASSWORD }}" >> .env
      shell: bash
    - name: Add IWF_API_URL
      run: echo "IWF_API_URL=${{ env.IWF_API_URL }}" >> .env
      shell: bash

    - name: Add IWF_SECRET_KEY
      run: echo "IWF_SECRET_KEY=${{ env.IWF_SECRET_KEY }}" >> .env
      shell: bash
    - name: Add IWF_API_CASE_URL
      run: echo "IWF_API_CASE_URL=${{ env.IWF_API_CASE_URL }}" >> .env
      shell: bash
    - name: Add IWF_REPORT_URL
      run: echo "IWF_REPORT_URL=${{ env.IWF_REPORT_URL }}" >> .env
      shell: bash
    - name: Add IWF_REPORT_SELF_SIGNED
      run: echo "IWF_REPORT_SELF_SIGNED=true" >> .env
      shell: bash

    - name: Add TWITTER_CONSUMER_KEY
      run: echo "TWITTER_CONSUMER_KEY=${{ env.TWITTER_CONSUMER_KEY }}" >> .env
      shell: bash
    - name: Add TWITTER_CONSUMER_SECRET
      run: echo "TWITTER_CONSUMER_SECRET=${{ env.TWITTER_CONSUMER_SECRET }}" >> .env
      shell: bash
    - name: Add TWITTER_ACCESS_TOKEN
      run: echo "TWITTER_ACCESS_TOKEN=${{ env.TWITTER_ACCESS_TOKEN }}" >> .env
      shell: bash
    - name: Add TWITTER_ACCESS_TOKEN_SECRET
      run: echo "TWITTER_ACCESS_TOKEN_SECRET=${{ env.TWITTER_ACCESS_TOKEN_SECRET }}" >> .env
      shell: bash
    - name: Add TWITTER_FLEX_FLOW_SID
      run: echo "TWITTER_FLEX_FLOW_SID=${{ env.TWITTER_FLEX_FLOW_SID }}" >> .env
      shell: bash
    - name: Add FACEBOOK_APP_SECRET
      run: echo "FACEBOOK_APP_SECRET=${{ env.FACEBOOK_APP_SECRET }}" >> .env
      shell: bash
    - name: Add FACEBOOK_PAGE_ACCESS_TOKEN
      run: echo "FACEBOOK_PAGE_ACCESS_TOKEN=${{ env.FACEBOOK_PAGE_ACCESS_TOKEN }}" >> .env
      shell: bash
    - name: Add INSTAGRAM_FLEX_FLOW_SID
      run: echo "INSTAGRAM_FLEX_FLOW_SID=${{ env.INSTAGRAM_FLEX_FLOW_SID }}" >> .env
      shell: bash
    - name: Add LINE_FLEX_FLOW_SID
      run: echo "LINE_FLEX_FLOW_SID=${{ env.LINE_FLEX_FLOW_SID }}" >> .env
      shell: bash
    - name: Add LINE_CHANNEL_SECRET
      run: echo "LINE_CHANNEL_SECRET=${{ env.LINE_CHANNEL_SECRET }}" >> .env
      shell: bash
    - name: Add LINE_CHANNEL_ACCESS_TOKEN
      run: echo "LINE_CHANNEL_ACCESS_TOKEN=${{ env.LINE_CHANNEL_ACCESS_TOKEN }}" >> .env
      shell: bash