# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: 'Zambia PRoduction release custom action'
description: 'Adds Instagram related environment variables to the Zambia Production environment'
runs:
  using: "composite"
  steps:
    # Set IWF credentials
    - name: Set IWF_API_USERNAME
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "IWF_API_USERNAME"
        env_variable_name: "IWF_API_USERNAME"
    - name: Set IWF_API_PASSWORD
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "IWF_API_PASSWORD"
        env_variable_name: "IWF_API_PASSWORD"
    - name: Set IWF_API_URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "IWF_API_URL"
        env_variable_name: "IWF_API_URL"
    - name: Set IWF_API_ENVIRONMENT
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "PROD_ZM_IWF_API_ENVIRONMENT"
        env_variable_name: "IWF_API_ENVIRONMENT"
    - name: Set IWF_API_COUNTRY_CODE
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "PROD_ZM_IWF_API_COUNTRY_CODE"
        env_variable_name: "IWF_API_COUNTRY_CODE"
    - name: Set IWF_API_CHANNEL_ID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "PROD_ZM_IWF_API_CHANNEL_ID"
        env_variable_name: "IWF_API_CHANNEL_ID"
    # Append environment variables
    - name: Add IWF_API_USERNAME
      run: echo "IWF_API_USERNAME=${{ env.IWF_API_USERNAME }}" >> .env
      shell: bash
    - name: Add IWF_API_PASSWORD
      run: echo "IWF_API_PASSWORD=${{ env.IWF_API_PASSWORD }}" >> .env
      shell: bash
    - name: Add IWF_API_URL
      run: echo "IWF_API_URL=${{ env.IWF_API_URL }}" >> .env
      shell: bash
    - name: Add IWF_API_ENVIRONMENT
      run: echo "IWF_API_ENVIRONMENT=${{ env.IWF_API_ENVIRONMENT }}" >> .env
      shell: bash
    - name: Add IWF_API_COUNTRY_CODE
      run: echo "IWF_API_COUNTRY_CODE=${{ env.IWF_API_COUNTRY_CODE }}" >> .env
      shell: bash
    - name: Add IWF_API_CHANNEL_ID
      run: echo "IWF_API_CHANNEL_ID=${{ env.IWF_API_CHANNEL_ID }}" >> .env
      shell: bash