name: 'Health Check'
description: 'Checks that the Serverless service is up and running'
inputs:
  account-sid:
    description: 'Twilio Account SID'
    required: true
  auth-token:
    description: 'Twilio Token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'