# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: 'Youthline Staging release custom action'
description: 'Sets up environment variables related to non-standard additional features in use in the staging environment'
inputs:
  account-sid:
    description: 'The Twilio Account SID for this account'
    required: true
runs:
  using: "composite"
  steps:

    # Modica environment variables
    - name: Set Modica App Name
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/modica/${{inputs.account-sid}}/app_name"
        env_variable_name: "MODICA_APP_NAME"
    - name: Set Modica App Password
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/modica/${{inputs.account-sid}}/app_password"
        env_variable_name: "MODICA_APP_PASSWORD"
    - name: Set Modica Studio Flow Sid
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/twilio/${{inputs.account-sid}}/modica_studio_flow_sid"
        env_variable_name: "MODICA_STUDIO_FLOW_SID"
    - name: Set helpline Modica Flex Messaging Mode (Programmable Chat or Conversations)
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/modica/${{inputs.account-sid}}/messaging_mode"
        env_variable_name: "MODICA_TWILIO_MESSAGING_MODE"

    # Append environment variables
    - name: Add MODICA_APP_NAME
      run: echo "MODICA_APP_NAME=${{ env.MODICA_APP_NAME }}" >> .env
      shell: bash
    - name: Add MODICA_APP_PASSWORD
      run: echo "MODICA_APP_PASSWORD=${{ env.MODICA_APP_PASSWORD }}" >> .env
      shell: bash
    - name: Add MODICA_STUDIO_FLOW_SID
      run: echo "MODICA_STUDIO_FLOW_SID=${{ env.MODICA_STUDIO_FLOW_SID }}" >> .env
      shell: bash
    - name: Add MODICA_TWILIO_MESSAGING_MODE
      run: echo "MODICA_TWILIO_MESSAGING_MODE=${{ env.MODICA_TWILIO_MESSAGING_MODE }}" >> .env
      shell: bash