name: 'Execute per-helpline custom action'
runs:
  using: "composite"
  steps:
    - name: Aselo Development release custom action
      if: github.workflow == format('Aselo Development release')
      uses: ./.github/actions/custom-actions/aselo_development_custom
    - name: Safernet Staging release custom action
      if: github.workflow == format('Safernet Staging release')
      uses: ./.github/actions/custom-actions/safernet_staging_custom