name: 'Execute per-helpline custom action'
description: Compound 'routing' action to load custom deployment actions for the helpline being deployed
runs:
  using: "composite"
  steps:
    - name: Thailand Staging release custom action
      if: github.workflow == format('Thailand Staging release')
      uses: ./.github/actions/custom-actions/thailand_staging_custom
    - name: Aarambh Staging release custom action
      if: github.workflow == format('Aarambh Staging release')
      uses: ./.github/actions/custom-actions/aarambh_staging_custom
    - name: Aarambh Production release custom action
      if: github.workflow == format('Aarambh Production release')
      uses: ./.github/actions/custom-actions/aarambh_production_custom
    - name: Aselo Development release custom action
      if: github.workflow == format('Aselo Development release')
      uses: ./.github/actions/custom-actions/aselo_development_custom
    - name: Aselo Beta release custom action
      if: github.workflow == format('Aselo Beta release')
      uses: ./.github/actions/custom-actions/aselo_beta_custom
    - name: SafeSpot Staging release custom action
      if: github.workflow == format('SafeSpot Staging release')
      uses: ./.github/actions/custom-actions/jamaica_staging_custom
    - name: SafeSpot Production release custom action
      if: github.workflow == format('SafeSpot Production release')
      uses: ./.github/actions/custom-actions/jamaica_production_custom
    - name: Malawi Staging release custom action
      if: github.workflow == format('Malawi Staging release')
      uses: ./.github/actions/custom-actions/malawi_staging_custom
    - name: Malawi Production release custom action
      if: github.workflow == format('Malawi Production release')
      uses: ./.github/actions/custom-actions/malawi_production_custom
    - name: Safernet Staging release custom action
      if: github.workflow == format('Safernet Staging release')
      uses: ./.github/actions/custom-actions/safernet_staging_custom
    - name: Safernet Production release custom action
      if: github.workflow == format('SaferNet Production release')
      uses: ./.github/actions/custom-actions/safernet_production_custom
    - name: TeGuio Colombia II Staging release custom action
      if: github.workflow == format('Te Guio Colombia II Staging release')
      uses: ./.github/actions/custom-actions/teguio_staging_custom
    - name: Zambia Staging release custom action
      if: github.workflow == format('Zambia Staging release')
      uses: ./.github/actions/custom-actions/zambia_staging_custom
    - name: Zambia Production release custom action
      if: github.workflow == format('Zambia Production release')
      uses: ./.github/actions/custom-actions/zambia_production_custom
