name: 'Execute per-helpline custom action'
description: Compound 'routing' action to load custom deployment actions for the helpline being deployed
runs:
  using: "composite"
  steps:
    - name: Aselo Development release custom action
      if: github.workflow == format('Aselo Development release')
      uses: ./.github/actions/custom-actions/aselo_development_custom
    - name: Safernet Staging release custom action
      if: github.workflow == format('Safernet Staging release')
      uses: ./.github/actions/custom-actions/safernet_staging_custom
    - name: Safernet Production release custom action
      if: github.workflow == format('SaferNet Production release')
      uses: ./.github/actions/custom-actions/safernet_production_custom
    - name: Zambia Staging release custom action
      if: github.workflow == format('Zambia Staging release')
      uses: ./.github/actions/custom-actions/zambia_staging_custom
    - name: Zambia Production release custom action
      if: github.workflow == format('Zambia Production release')
      uses: ./.github/actions/custom-actions/zambia_production_custom

