name: 'Execute per-helpline custom action'
runs:
  using: "composite"
  steps:
    - name: Aselo Development release custom action
      if: github.workflow == format('Aselo Development release')
      uses: ./.github/actions/custom-actions/aselo_development_custom