# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: 'Execute per-helpline custom action'
description: Compound 'routing' action to load custom deployment actions for the helpline being deployed
inputs:
  helpline-name:
    description: 'The identifier in the format "<short helpline>_<short env>" used for this helpline'
    required: true
  account-sid:
    description: 'The Twilio Account SID for this account'
    required: true

runs:
  using: "composite"
  steps:
    - name: Childline Thailand Staging release custom action
      if: inputs.helpline-name == format('TH_STG')
      uses: ./.github/actions/custom-actions/thailand_staging_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Childline Thailand Production release custom action
      if: inputs.helpline-name == format('TH_PROD')
      uses: ./.github/actions/custom-actions/thailand_production_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Aarambh Staging release custom action
      if: inputs.helpline-name == format('IN_STG')
      uses: ./.github/actions/custom-actions/aarambh_staging_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Aarambh Production release custom action
      if: inputs.helpline-name == format('IN_PROD')
      uses: ./.github/actions/custom-actions/aarambh_production_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Aselo Development release custom action
      if: inputs.helpline-name == format('AS_DEV')
      uses: ./.github/actions/custom-actions/aselo_development_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Aselo Production release custom action
      if: inputs.helpline-name == format('AS_PROD')
      uses: ./.github/actions/custom-actions/aselo_production_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Aselo Staging release custom action
      if: inputs.helpline-name == format('AS_STG')
      uses: ./.github/actions/custom-actions/aselo_staging_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: SafeSpot Staging release custom action
      if: inputs.helpline-name == format('JM_STG')
      uses: ./.github/actions/custom-actions/jamaica_staging_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: SafeSpot Production release custom action
      if: inputs.helpline-name == format('JM_PROD')
      uses: ./.github/actions/custom-actions/jamaica_production_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Malawi Staging release custom action
      if: inputs.helpline-name == format('MW_STG')
      uses: ./.github/actions/custom-actions/malawi_staging_custom
    - name: Malawi Production release custom action
      if: inputs.helpline-name == format('MW_PROD')
      uses: ./.github/actions/custom-actions/malawi_production_custom
    - name: Safernet Staging release custom action
      if: inputs.helpline-name == format('BR_STG')
      uses: ./.github/actions/custom-actions/safernet_staging_custom
    - name: Safernet Production release custom action
      if: inputs.helpline-name == format('BR_PROD')
      uses: ./.github/actions/custom-actions/safernet_production_custom
    - name: TeGuio Colombia Staging release custom action
      if: inputs.helpline-name == format('CO_STG')
      uses: ./.github/actions/custom-actions/teguio_staging_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: TeGuio Colombia Production release custom action
      if: inputs.helpline-name == format('CO_PROD')
      uses: ./.github/actions/custom-actions/teguio_production_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Kellimni Malta Production release custom action
      if: inputs.helpline-name == format('MT_PROD')
      uses: ./.github/actions/custom-actions/kellimni_production_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Kellimni Malta Staging release custom action
      if: inputs.helpline-name == format('MT_STG')
      uses: ./.github/actions/custom-actions/kellimni_staging_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Zambia Staging release custom action
      if: inputs.helpline-name == format('ZM_STG')
      uses: ./.github/actions/custom-actions/zambia_staging_custom
    - name: Zambia Production release custom action
      if: inputs.helpline-name == format('ZM_PROD')
      uses: ./.github/actions/custom-actions/zambia_production_custom
    - name: E2E Development release custom action
      if: inputs.helpline-name == format('E2E_DEV')
      uses: ./.github/actions/custom-actions/e2e_development_custom
    - name: Youthline Production release custom action
      if: inputs.helpline-name == format('NZ_PROD')
      uses: ./.github/actions/custom-actions/youthline_production_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: Youthline Staging release custom action
      if: inputs.helpline-name == format('NZ_STG')
      uses: ./.github/actions/custom-actions/youthline_staging_custom
      with:
        account-sid: ${{ inputs.account-sid }}

    - name: C Sema Production release custom action
      if: inputs.helpline-name == format('TZ_PROD')
      uses: ./.github/actions/custom-actions/youthline_production_custom
      with:
        account-sid: ${{ inputs.account-sid }}
    - name: C Sema Staging release custom action
      if: inputs.helpline-name == format('TZ_STG')
      uses: ./.github/actions/custom-actions/youthline_staging_custom
      with:
        account-sid: ${{ inputs.account-sid }}