# Install the Twilio CLI and the serverless plugin then deploy the function
name: 'main-action'
description: 'Install the Twilio CLI and the serverless plugin then deploy the function'
inputs:
  account-sid:
    description: 'Twilio Account SID'
    required: true
  auth-token:
    description: 'Twilio Token'
    required: true
  workspace-sid:  
      description: 'Twilio Workspace SID'
      required: true
  transfer-workflow-sid:  
    description: 'Chat Transfer Workflow SID'
    required: true
  sync-service-api-key:  
    description: 'Sync Service API Key'
    required: true
  sync-service-api-secret:  
    description: 'Sync Service API Secret'
    required: true
  sync-service-sid:
    description: 'Sync Service SID'
    required: true
  chat-service-sid:
    description: 'Chat Service SID'
    required: true
  operating-info-key:
    description: 'Operating Info Key'
    required: true
runs:
  using: "composite"
  steps:
    # Prepare everything to compile the serverless application with proper env
    - name: Create environment variable file
      run: touch .env
      shell: bash
    - name: Fill .env
      run: |
          cat <<EOT >> .env
          TWILIO_WORKSPACE_SID=${{ inputs.workspace-sid }}
          TWILIO_CHAT_TRANSFER_WORKFLOW_SID=${{ inputs.transfer-workflow-sid }}
          SYNC_SERVICE_API_KEY=${{ inputs.sync-service-api-key }}
          SYNC_SERVICE_API_SECRET=${{ inputs.sync-service-api-secret }}
          SYNC_SERVICE_SID=${{ inputs.sync-service-sid }}
          CHAT_SERVICE_SID=${{ inputs.chat-service-sid }}
          OPERATING_INFO_KEY=${{ inputs.operating-info-key }}
          EOT
      shell: bash
    # Install dependencies for the twilio functions
    - name: Install dependencies for the twilio functions
      run: npm ci
      shell: bash
    # Compile typescript to javascript
    - name: Transpile typescript to javascript
      run: npx tsc
      shell: bash
    # Install Twilio CLI and run deploy command
    - name: Install Twilio CLI and run deploy command
      run: npm install twilio-cli -g && twilio plugins:install @twilio-labs/plugin-serverless && twilio serverless:deploy --runtime=node12 --service-name=serverless --environment=dev --force
      env:
        TWILIO_ACCOUNT_SID: ${{ inputs.account-sid }}
        TWILIO_AUTH_TOKEN: ${{ inputs.auth-token }}
      shell: bash
    - run: twilio serverless:deploy --runtime=node12 --service-name=serverless --environment=production --force
      env:
        TWILIO_ACCOUNT_SID: ${{ inputs.account-sid }}
        TWILIO_AUTH_TOKEN: ${{ inputs.auth-token }}
      shell: bash