# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

name: 'Aselo Staging release custom action'
description: 'Sets up environment variables related to non-standard additional features in use in the staging environment'
inputs:
  account-sid:
    description: 'The Twilio Account SID for this account'
    required: true
runs:
  using: "composite"
  steps:
    # Telegram environment variables
    - name: Set Telegram Flex Bot Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/telegram/${{inputs.account-sid}}/flex_bot_token"
        env_variable_name: "TELEGRAM_FLEX_BOT_TOKEN"
    - name: Set Telegram Bot Api Secret Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/telegram/${{inputs.account-sid}}/bot_api_secret_token"
        env_variable_name: "TELEGRAM_BOT_API_SECRET_TOKEN"
    - name: Set helpline Telegram Studio Flow SID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/twilio/${{inputs.account-sid}}/telegram_studio_flow_sid"
        env_variable_name: "TELEGRAM_STUDIO_FLOW_SID"

    - name: Set helpline serverless URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/serverless/${{inputs.account-sid}}/base_url"
        env_variable_name: "SERVERLESS_BASE_URL"
    - name: Set Telegram flex bot webhook
      shell: bash
      run: |
        curl --request POST \
        --header "Content-Type: application/json" \
        --url "https://api.telegram.org/bot${{ env.TELEGRAM_FLEX_BOT_TOKEN }}/setWebhook" \
        --data '{ "url": "${{ env.SERVERLESS_BASE_URL }}/webhooks/telegram/TelegramToFlex", "secret_token": "${{ env.TELEGRAM_BOT_API_SECRET_TOKEN }}" }'
 # Line environment variables
    - name: Set Line Channel Secret
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/line/${{inputs.account-sid}}/channel_secret"
        env_variable_name: "LINE_CHANNEL_SECRET"
    - name: Set Line Channel Access Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/line/${{inputs.account-sid}}/channel_access_token"
        env_variable_name: "LINE_CHANNEL_ACCESS_TOKEN"
    - name: Set helpline Line Studio Flow SID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/twilio/${{inputs.account-sid}}/line_studio_flow_sid"
        env_variable_name: "LINE_STUDIO_FLOW_SID"
    - name: Set helpline Line Flex Messaging Mode (Programmable Chat or Conversations)
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/line/${{inputs.account-sid}}/messaging_mode"
        env_variable_name: "LINE_TWILIO_MESSAGING_MODE"

# Set Instagram variables
    - name: Set Aselo Facebook App Secret
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "FACEBOOK_APP_SECRET"
        env_variable_name: "FACEBOOK_APP_SECRET"
    - name: Set helpline Facebook Page Access Token
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "FACEBOOK_PAGE_ACCESS_TOKEN_398416306680981_Aselo-Staging"
        env_variable_name: "FACEBOOK_PAGE_ACCESS_TOKEN"
    - name: Set helpline Instagram Studio Flow SID
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/twilio/${{inputs.account-sid}}/instagram_studio_flow_sid"
        env_variable_name: "INSTAGRAM_STUDIO_FLOW_SID"
    - name: Set helpline Instagram Flex Messaging Mode (Programmable Chat or Conversations)
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/instagram/${{inputs.account-sid}}/messaging_mode"
        env_variable_name: "INSTAGRAM_TWILIO_MESSAGING_MODE"

    # Modica environment variables
    - name: Set Modica App Name
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/modica/${{inputs.account-sid}}/app_name"
        env_variable_name: "MODICA_APP_NAME"
    - name: Set Modica App Password
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/modica/${{inputs.account-sid}}/app_password"
        env_variable_name: "MODICA_APP_PASSWORD"
    - name: Set Modica Studio Flow Sid
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/twilio/${{inputs.account-sid}}/modica_studio_flow_sid"
        env_variable_name: "MODICA_STUDIO_FLOW_SID"
    - name: Set helpline Modica Flex Messaging Mode (Programmable Chat or Conversations)
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/modica/${{inputs.account-sid}}/messaging_mode"
        env_variable_name: "MODICA_TWILIO_MESSAGING_MODE"
    - name: Set test API URL
      uses: "marvinpinto/action-inject-ssm-secrets@latest"
      with:
        ssm_parameter: "/staging/modica/${{inputs.account-sid}}/test_send_message_url"
        env_variable_name: "MODICA_TEST_SEND_MESSAGE_URL"

    # Append environment variables
    - name: Add TELEGRAM_FLEX_BOT_TOKEN
      run: echo "TELEGRAM_FLEX_BOT_TOKEN=${{ env.TELEGRAM_FLEX_BOT_TOKEN }}" >> .env
      shell: bash
    - name: Add TELEGRAM_BOT_API_SECRET_TOKEN
      run: echo "TELEGRAM_BOT_API_SECRET_TOKEN=${{ env.TELEGRAM_BOT_API_SECRET_TOKEN }}" >> .env
      shell: bash
    - name: Add TELEGRAM_STUDIO_FLOW_SID
      run: echo "TELEGRAM_STUDIO_FLOW_SID=${{ env.TELEGRAM_STUDIO_FLOW_SID }}" >> .env
      shell: bash
    - name: Add LINE_CHANNEL_SECRET
      run: echo "LINE_CHANNEL_SECRET=${{ env.LINE_CHANNEL_SECRET }}" >> .env
      shell: bash
    - name: Add LINE_CHANNEL_ACCESS_TOKEN
      run: echo "LINE_CHANNEL_ACCESS_TOKEN=${{ env.LINE_CHANNEL_ACCESS_TOKEN }}" >> .env
      shell: bash
    - name: Add LINE_STUDIO_FLOW_SID
      run: echo "LINE_STUDIO_FLOW_SID=${{ env.LINE_STUDIO_FLOW_SID }}" >> .env
      shell: bash
    - name: Add LINE_TWILIO_MESSAGING_MODE
      run: echo "LINE_TWILIO_MESSAGING_MODE=${{ env.LINE_TWILIO_MESSAGING_MODE }}" >> .env
      shell: bash
    - name: Add FACEBOOK_APP_SECRET
      run: echo "FACEBOOK_APP_SECRET=${{ env.FACEBOOK_APP_SECRET }}" >> .env
      shell: bash
    - name: Add FACEBOOK_PAGE_ACCESS_TOKEN
      run: echo "FACEBOOK_PAGE_ACCESS_TOKEN=${{ env.FACEBOOK_PAGE_ACCESS_TOKEN }}" >> .env
      shell: bash
    - name: Add INSTAGRAM_STUDIO_FLOW_SID
      run: echo "INSTAGRAM_STUDIO_FLOW_SID=${{ env.INSTAGRAM_STUDIO_FLOW_SID }}" >> .env
      shell: bash
    - name: Add INSTAGRAM_TWILIO_MESSAGING_MODE
      run: echo "INSTAGRAM_TWILIO_MESSAGING_MODE=${{ env.INSTAGRAM_TWILIO_MESSAGING_MODE }}" >> .env
      shell: bash
    - name: Add MODICA_APP_NAME
      run: echo "MODICA_APP_NAME=${{ env.MODICA_APP_NAME }}" >> .env
      shell: bash
    - name: Add MODICA_APP_PASSWORD
      run: echo "MODICA_APP_PASSWORD=${{ env.MODICA_APP_PASSWORD }}" >> .env
      shell: bash
    - name: Add MODICA_STUDIO_FLOW_SID
      run: echo "MODICA_STUDIO_FLOW_SID=${{ env.MODICA_STUDIO_FLOW_SID }}" >> .env
      shell: bash
    - name: Add MODICA_TWILIO_MESSAGING_MODE
      run: echo "MODICA_TWILIO_MESSAGING_MODE=${{ env.MODICA_TWILIO_MESSAGING_MODE }}" >> .env
      shell: bash
    - name: Add MODICA_TEST_SEND_MESSAGE_URL
      run: echo "MODICA_TEST_SEND_MESSAGE_URL=${{ env.MODICA_TEST_SEND_MESSAGE_URL }}" >> .env
      shell: bash

