# Copyright (C) 2021-2023 Technology Matters
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/.

# This is a basic workflow to publish a Twilio function with Github Actions

name: Kek Vonal Staging release

on: workflow_dispatch
jobs:
  deploy:
    uses: ./.github/workflows/custom_helpline.yml
    secrets: inherit
    with:
      helpline_code: 'HU'
      environment_code: 'STG'
      environment: 'staging'
      changelog: 'Deploying individual account'
